name: learn-github-actions
run-name:
on:
  pull_request:
    types:
      - closed
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git commit --allow-empty -m "Empty-Commit"
          git push
